version: '3.3'

services:
  pictrs:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${USER_ID:-1000}"
        GID: "${GROUP_ID:-1000}"
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      - RUST_LOG=info,pict_rs=debug
    volumes:
      - ../../:/opt/build/repo
