version: '3.3'

services:
  pictrs:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
      args:
        UID: "${USER_ID:-1000}"
        GID: "${GROUP_ID:-1000}"
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    environment:
      - RUST_LOG=info,pict_rs=debug
    volumes:
      - ./volumes/pictrs:/mnt
