[package]
name = "pict-rs"
description = "A simple image hosting service"
version = "0.3.0-alpha.4"
authors = ["asonix <asonix@asonix.dog>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://git.asonix.dog/asonix/pict-rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-form-data = "0.5.0"
actix-fs = { git = "https://git.asonix.dog/asonix/actix-fs", branch = "main" }
actix-rt = "1.1.1"
actix-web = { version = "3.0.1", default-features = false, features = ["rustls"] }
anyhow = "1.0"
base64 = "0.13.0"
bytes = "0.5"
futures = "0.3.4"
magick_rust = { version = "0.14.0", git = "https://github.com/nlfiedler/magick-rust" }
mime = "0.3.1"
once_cell = "1.4.0"
rand = "0.7.3"
rexiv2 = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.0"
sled = { version = "0.34.4" }
structopt = "0.3.14"
thiserror = "1.0"
time = { version = "0.2.23", features = ["serde"] }
tracing = "0.1.15"
tracing-futures = "0.2.4"
tracing-subscriber = { version = "0.2.5", features = ["fmt", "tracing-log"] }
uuid = { version = "0.8", features = ["v4"] }

[dependencies.ffmpeg-next]
version = "4.3.7"
default-features = false
features = ["codec", "filter", "device", "format", "resampling", "postprocessing", "software-resampling", "software-scaling"]

[dependencies.ffmpeg-sys-next]
version = "4.3.5"
