[package]
name = "pict-rs"
description = "A simple image hosting service"
version = "0.2.0-alpha.3"
authors = ["asonix <asonix@asonix.dog>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://git.asonix.dog/asonix/pict-rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-form-data = { git = "https://git.asonix.dog/Aardwolf/actix-form-data" }
actix-fs = { git = "https://git.asonix.dog/asonix/actix-fs", branch = "main" }
actix-rt = "1.1.1"
actix-web = { version = "3.0.0-alpha.2", features = ["rustls"] }
anyhow = "1.0"
base64 = "0.12.1"
bytes = "0.5"
futures = "0.3.4"
magick_rust = { version = "0.14.0", git = "https://git.asonix.dog/asonix/magick-rust" }
mime = "0.3.1"
once_cell = "1.4.0"
rand = "0.7.3"
rexiv2 = { version = "0.9.0", git = "https://git.asonix.dog/asonix/rexiv2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.0"
sled = "0.32.0"
structopt = "0.3.14"
thiserror = "1.0"
tracing = "0.1.15"
tracing-futures = "0.2.4"
tracing-subscriber = { version = "0.2.5", features = ["fmt", "tracing-log"] }
uuid = { version = "0.8", features = ["v4"] }

[dependencies.ffmpeg-next]
version = "4.3.0"
git = "https://git.asonix.dog/asonix/rust-ffmpeg"
branch = "main"
default-features = false
features = ["ffmpeg42", "codec", "filter", "device", "format", "resampling", "postprocessing", "software-resampling", "software-scaling"]

[dependencies.ffmpeg-sys-next]
version = "4.3.0"
git = "https://git.asonix.dog/asonix/rust-ffmpeg-sys"
branch = "main"
