version: '3.3'

services:
  pictrs:
    image: asonix/pictrs:v0.1.0-r5
    user: root
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    environment:
      - PICTRS_PATH=/app/data
    volumes:
      - ./volumes/pictrs:/app/data
